### ISSUE TITLE
path это не re_path

### ISSUE THREAD

**Issue by pbdgk** [VladLungul/rent#1]
https://github.com/VladLungul/rent/blob/c975a470fedc270df1155182138c00d544d8b41f/rentsite/rentsite/urls.py#L22

в path не надо передавать символы начала и конца строки регулярных выражений.
они используются в re_path

**Comment by pbdgk** [comment]
оставь просто path('accounts/', include('owner.urls')),

**Comment by VladLungul** [comment]
done
